# Generated by Django 2.0.7 on 2018-07-11 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('zip', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{2}-[0-9]{3}$', message='Zip code has format xx-xxx')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^([^\\d!@#$%^&*])+$', message='Enter letters and/or spaces')])),
            ],
            options={
                'verbose_name_plural': 'Entries',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ZipCodeCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{2}-[0-9]{3}$', message='Zip code has format xx-xxx')])),
                ('counter', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
