# Generated by Django 2.0.7 on 2018-07-10 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userentry',
            name='name',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[a-Z ]$', message='Enter letters and/or spaces')]),
        ),
    ]
