# Generated by Django 2.0.7 on 2018-07-10 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180710_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userentry',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', message='Enter letters and/or spaces')]),
        ),
    ]
