# Generated by Django 2.0.7 on 2018-07-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180710_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userentry',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
